apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Chart.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - name: tf-jupyter-gpu
        resources:
          requests:
            cpu: "{{ .Values.cpu.requests }}"
            memory: "{{ .Values.memory.requests }}"
            alpha.kubernetes.io/nvidia-gpu: 1
          limits:
            cpu: "{{ .Values.cpu.limits }}"
            memory: "{{ .Values.memory.limits }}"
            alpha.kubernetes.io/nvidia-gpu: 1
        image: "{{ printf "%s:%s" .Values.image.Name .Values.image.Tag }}"
        ports:
        - containerPort: 8888
          name: jupyter
        env:
        - name: LD_LIBRARY_PATH
          value: "$LD_LIBRARY_PATH:/usr/lib/nvidia:/usr/lib/cuda:/usr/local/cuda/extras/CUPTI/lib64"        
        volumeMounts:
        - name: notebooks
          mountPath: "/notebooks/{{ .Chart.Name }}"
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/lib/nvidia
          name: lib
        - mountPath: /usr/lib/cuda
          name: libcuda
        - mountPath: /usr/local/cuda/extras/CUPTI/lib64
          name: capti
      volumes:
      - name: notebooks
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: "{{ printf "%s-%s" .Release.Name .Chart.Name | trunc 24 }}"
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: bin
        hostPath: 
          path: /usr/lib/nvidia-375/bin
      - name: lib
        hostPath: 
          path: /usr/lib/nvidia-375
      - name: libcuda
        hostPath: 
          path: /usr/lib/x86_64-linux-gnu
      - hostPath:
          path: /usr/local/cuda/extras/CUPTI/lib64
        name: capti
