apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Chart.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 8888
      targetPort: 8888
    - port: 6006
      targetPort: 6006
  selector:
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}"
